### ISSUE TITLE
Saving portal to file.

### ISSUE THREAD

**Issue by MatthewFoster02** [S010MON/multi-agent-surveillance#146]
Two bugs.

1. If a portal object has been drawn to the canvas and we try to create the map file, we get an error.

2. Even when we undo a rectangle object from the canvas, it still gets saved to the map file created after.

**Comment by Jolijn2020** [comment]
I got the same bug, and I fixed in in my branch already
I'll make a seperate branch and fix it in there too

**Comment by Jolijn2020** [comment]
nvm, I had I similar bug, but not the same (mine was that there was a not initialized arrayList for a portals list, but that list doesn't exist in main yet)
