### ISSUE TITLE
WallFollowAgent - Glass

### ISSUE THREAD

**Issue by S010MON** [S010MON/multi-agent-surveillance#155]
The wall follow agent is currently working well, until it encounters glass.  As it can see in that direction, it thinks it can move that way as well.  The agent may need to receive feedback when it touches (i.e. gets blocked from moving) as currently it just is denied without any feedback.

**Comment by laurajogi** [comment]
WF agent can move past glass now, handling that in WallFollowAgent-heuristics-algo branch
