### ISSUE TITLE
Class: Settings

### ISSUE THREAD

**Issue by S010MON** [S010MON/multi-agent-surveillance#18]
Create a `Settings` class that wraps up all the information in the file in an immutable format. Elements should be kept private and only be read through getter methods to avoid data corruption.

**Comment by MatthewFoster02** [comment]
Settings class implemented, texture and portal fields currently are rectangle 2D arrays but should be their own object such that they can hold the rectangle they cover, the x, y position of the point to be teleported to, and the double orientation (if we plan to make use of orientations). Setter methods could be added if we would like to mutate the map in the code, or fields set to final in Settings if we do not wish to mutate them. Also, I am not sure if I am following the workflow correctly, I understand that usually you would write tests first but I felt this was not appropriate for this settings class and I am unsure if I should pull request now or when the file-parser class is finished as this branch is set up to implement both.

**Comment by S010MON** [comment]
> I understand that usually you would write tests first but I felt this was not appropriate for this settings class
Completely fine - it's a data class so there isn't anything to test
