### ISSUE TITLE
Class: AgentImp

### ISSUE THREAD

**Issue by Jolijn2020** [S010MON/multi-agent-surveillance#28]
add constructor with parameters maxWalk, maxRun and timeStep(as this is specified by the testmap, and not a constant)

add method setDirection(Vector directions) to change direction
add method setSpeed(double speed) to change speed

update move() method to actually move (does not yet check for walls)

**Comment by S010MON** [comment]
@Jolijn2020 : 
> _"add constructor with parameters maxWalk, maxRun and timeStep(as this is specified by the testmap, and not a constant)"_

This is not yet required for `AgentImp`. The implementation class is a class that sets the default behaviour of all agents that are implementing the `Agent` interface.  This class will not be used, it is a framework for other devs to override the methods with their own implementations.  

> add method setDirection(Vector directions) to change direction
> add method setSpeed(double speed) to change speed

:+1:  both good points, see issues #33 and #32  (which 33 depends on) that you may need to do in the same class
