### ISSUE TITLE
Baseline Agent Exploration Experiment

### ISSUE THREAD

**Issue by trav-d13** [S010MON/multi-agent-surveillance#331]
Experimentation to determine the number of unit ticks to explore 90% of a given experiment map (1-5), for a range of agents {1, 2, 4, 5, 6, 10}. Agents to be tested include {Random, Aco Baseline, Aco Momentum, Aco Momentum Spiral Avoidance, WallFollow}. 
Collected .csv files will be uploaded to the project google drive.

**Comment by S010MON** [comment]
I think this has been dealt with already?  Closing unless you still need it?
