### ISSUE TITLE
Limit Field of View

### ISSUE THREAD

**Issue by S010MON** [S010MON/multi-agent-surveillance#79]
Create a function that takes in an `ArrayList<Ray>` and a `Vector leftLimit` and `Vector rightLimit` and outputs a new ArrayList containing all the vectors that fall within the left and right limits (where left is the first and right is the second direction encountered when moving clockwise from zero)

Add a check that, when the left  -> right is or exceeds 360, then the entire array is returned.

**Comment by Jolijn2020** [comment]
clockwise, from left to right, return all rays between those points

**Comment by Jolijn2020** [comment]
new class, in controller, "FieldOfView"
